### ISSUE TITLE
DEBUG_PAGES not working

### ISSUE THREAD

**Issue by dobesv** [Magnetme/prerender-docker#15]
If I set the `DEBUG_PAGES` environment variable, the server fails to startup:

```
22:16:27 0|server   | TypeError: prerender.logger is not a function
22:16:27 0|server   |     at Object.&lt;anonymous&gt; (/usr/src/app/server.js:27:23)
22:16:27 0|server   |     at Module._compile (module.js:643:30)
22:16:27 0|server   |     at Object.Module._extensions..js (module.js:654:10)
22:16:27 0|server   |     at Module.load (module.js:556:32)
22:16:27 0|server   |     at tryModuleLoad (module.js:499:12)
22:16:27 0|server   |     at Function.Module._load (module.js:491:3)
22:16:27 0|server   |     at /usr/src/app/node_modules/pm2/lib/ProcessContainer.js:331:23
22:16:27 0|server   |     at /usr/src/app/node_modules/pm2/node_modules/async/dist/async.js:473:16
22:16:27 0|server   |     at next (/usr/src/app/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
22:16:27 0|server   |     at /usr/src/app/node_modules/pm2/node_modules/async/dist/async.js:958:16
```

I'm using `magnetme/prerender-docker:v2.3.0`

**Comment by rogierslag** [comment]
Fixed in https://github.com/Magnetme/prerender-docker/commit/e552a385c9e4d1df08f6f218dc75f48a1036b9e2 and will be released as `2.3.1` within a few minutes!

Thanks for reporting!
