### ISSUE TITLE
Invalid InterceptionId and WebSocket is not open: readyState 2 (CLOSING)

### ISSUE THREAD

**Issue by vdt-mik** [Magnetme/prerender-docker#26]
Hi! i try to use your docker image for my app which running in the GKE cluster. I faced with that errors: 
```
Error: WebSocket is not open: readyState 2 (CLOSING)
at WebSocket.send (/usr/src/app/node_modules/ws/lib/websocket.js:329:19)
at Chrome._enqueueCommand (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:277:18)
at Promise (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:85:22)
at new Promise (<anonymous>)
at Chrome.send (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:84:20)
at Object.handler [as continueInterceptedRequest] (/usr/src/app/node_modules/chrome-remote-interface/lib/api.js:32:23)
at Chrome.req.prerender.tab.Network.requestIntercepted (/usr/src/app/node_modules/prerender/lib/plugins/blockResources.js:62:30)
 at Chrome.emit (events.js:198:13)
at Chrome._handleMessage (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:266:18)
at WebSocket._ws.on (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:230:22)
```
and 

```
{ Error: Invalid InterceptionId.
at _enqueueCommand (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:90:34)
at Chrome._handleMessage (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:252:17)
at WebSocket._ws.on (/usr/src/app/node_modules/chrome-remote-interface/lib/chrome.js:230:22)
at WebSocket.emit (events.js:198:13)
at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:789:20)
at Receiver.emit (events.js:198:13)
at Receiver.dataMessage (/usr/src/app/node_modules/ws/lib/receiver.js:422:14)
at perMessageDeflate.decompress (/usr/src/app/node_modules/ws/lib/receiver.js:379:23)
at _decompress (/usr/src/app/node_modules/ws/lib/permessage-deflate.js:298:9)
at _inflate.flush (/usr/src/app/node_modules/ws/lib/permessage-deflate.js:376:7)
request:
{ method: 'Network.continueInterceptedRequest',
params: { interceptionId: 'interception-job-2348.1' } },
response: { code: -32602, message: 'Invalid InterceptionId.' } }
```

after these errors prerender gets a 502 error on every response. "getting https://example.com -> response not sent for https://example.com" and a pm2 doesn`t kill a chrome and only when I restart pm2 process manually it helps but some times it will happen again.

My configuraion: 
```
0|server   | Starting with options: { pageDoneCheckInterval: 500,
0|server   |   pageLoadTimeout: 20000,
0|server   |   waitAfterLastRequest: 250,
0|server   |   chromeFlags:
0|server   |    [ '--no-sandbox',
0|server   |      '--headless',
0|server   |      '--disable-gpu',
0|server   |      '--remote-debugging-port=9222',
0|server   |      '--hide-scrollbars',
0|server   |      '--disable-dev-shm-usage' ] }
0|server   | 2019-09-04T11:31:37.159Z Starting Prerender
0|server   | 2019-09-04T11:31:37.160Z Starting Chrome
0|server   | 2019-09-04T11:31:37.168Z Prerender server accepting requests on port 3000
0|server   | 2019-09-04T11:31:37.683Z Started Chrome: HeadlessChrome/76.0.3809.87
```

**Comment by rogierslag** [comment]
Does the instance run for a while without problems, or do problems occur immediately?

**Comment by vdt-mik** [comment]
the instance run for a while without problems but after 5-10minutes it can start

**Comment by vdt-mik** [comment]
Also, I want to add readiness and liveness probes but your health check localhost:3000/_health is not suited for checking working a prerender. Can you help me with it? How I can check that a prerender work? I found only one solution, once of 5 sec try to render some sites.
